"use strict";
let strArray = ["hey", "jet", "get"];
let strNumArr = ['strat', "Les Paul", 5150];
let mixedData = ["Evdg", 2000, true,];
strArray[0] = "dilnawaz";
strArray.push("sahila");
strNumArr[0] = 18564;
strNumArr.unshift("jim");
console.log(strNumArr);
let test = [];
let bands = [];
bands.push("a");
console.log(bands);
let tuple = ['Dil', 42, true];
let array = ['Dil', 15, "true"];
tuple[0] = "hello";
array[0] = "dbedge";
